### ISSUE TITLE
关于叠加echarts后leaflet本身要素事件失效的问题

### ISSUE THREAD

**Issue by tutuxxx** [wandergis/leaflet-echarts#1]
当我在已有的leaflet矢量图层上叠加echarts后，矢量图层中要素的点击事件失效了，请问该怎么解决呢？
问题已解决：在echarts叠加层添加pointer-events:none;即可

**Comment by wandergis** [comment]
嗯嗯，非常感谢你提出的问题和解决方案。

**Comment by wandergis** [comment]
另外你可以试试我新针对echarts3写的扩展，https://github.com/wandergis/leaflet-echarts3

**Comment by tutuxxx** [comment]
好的，已经在试了，很赞！
