### ISSUE TITLE
迁徙图左上方会（以挺大的随机概率）出现一个橙红色的点，有办法解决吗？

### ISSUE THREAD

**Issue by SunnyCat2013** [wandergis/leaflet-echarts#4]
<img width="1276" alt="screen shot 2016-11-03 at 10 30 05 am" src="https://cloud.githubusercontent.com/assets/4412909/19954140/8f2928d0-a1b0-11e6-8ba2-f93bbd7a0838.png">

**Comment by SunnyCat2013** [comment]
逼死强迫症啊 啊 啊啊。。。。

**Comment by wandergis** [comment]
已知悉，后面不忙的时候会重新写一个版本 目前实在是太忙了，没时间去维护

**Comment by SunnyCat2013** [comment]
呃，我仔细检查了我的配置。。应该不是配置的问题。。。无力看源码啊。。
坐等大神更新~~
